`timescale 1 ns/100 ps
// Version: 9.1 SPB 9.1.0.22


module Ram4096x16_TPort(WD,RD,WEN,REN,WADDR,RADDR,WCLK,RCLK);
input [15:0] WD;
output [15:0] RD;
input  WEN, REN;
input [11:0] WADDR, RADDR;
input WCLK, RCLK;

    wire WEAP, WEBP, VCC, GND;
    
    VCC VCC_1_net(.Y(VCC));
    GND GND_1_net(.Y(GND));
    RAM4K9 Ram4096x16_TPort_R0C1(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[1]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[1]));
    RAM4K9 Ram4096x16_TPort_R0C7(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[7]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[7]));
    RAM4K9 Ram4096x16_TPort_R0C13(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[13]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[13]));
    RAM4K9 Ram4096x16_TPort_R0C5(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[5]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[5]));
    RAM4K9 Ram4096x16_TPort_R0C12(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[12]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[12]));
    RAM4K9 Ram4096x16_TPort_R0C6(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[6]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[6]));
    RAM4K9 Ram4096x16_TPort_R0C3(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[3]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[3]));
    RAM4K9 Ram4096x16_TPort_R0C2(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[2]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[2]));
    RAM4K9 Ram4096x16_TPort_R0C0(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[0]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[0]));
    INV WEBUBBLEB(.A(REN), .Y(WEBP));
    RAM4K9 Ram4096x16_TPort_R0C8(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[8]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[8]));
    RAM4K9 Ram4096x16_TPort_R0C15(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[15]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[15]));
    RAM4K9 Ram4096x16_TPort_R0C10(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[10]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[10]));
    RAM4K9 Ram4096x16_TPort_R0C4(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[4]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[4]));
    RAM4K9 Ram4096x16_TPort_R0C9(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[9]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[9]));
    RAM4K9 Ram4096x16_TPort_R0C14(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[14]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[14]));
    INV WEBUBBLEA(.A(WEN), .Y(WEAP));
    RAM4K9 Ram4096x16_TPort_R0C11(.ADDRA11(WADDR[11]), .ADDRA10(
        WADDR[10]), .ADDRA9(WADDR[9]), .ADDRA8(WADDR[8]), .ADDRA7(
        WADDR[7]), .ADDRA6(WADDR[6]), .ADDRA5(WADDR[5]), .ADDRA4(
        WADDR[4]), .ADDRA3(WADDR[3]), .ADDRA2(WADDR[2]), .ADDRA1(
        WADDR[1]), .ADDRA0(WADDR[0]), .ADDRB11(RADDR[11]), 
        .ADDRB10(RADDR[10]), .ADDRB9(RADDR[9]), .ADDRB8(RADDR[8]), 
        .ADDRB7(RADDR[7]), .ADDRB6(RADDR[6]), .ADDRB5(RADDR[5]), 
        .ADDRB4(RADDR[4]), .ADDRB3(RADDR[3]), .ADDRB2(RADDR[2]), 
        .ADDRB1(RADDR[1]), .ADDRB0(RADDR[0]), .DINA8(GND), .DINA7(
        GND), .DINA6(GND), .DINA5(GND), .DINA4(GND), .DINA3(GND), 
        .DINA2(GND), .DINA1(GND), .DINA0(WD[11]), .DINB8(GND), 
        .DINB7(GND), .DINB6(GND), .DINB5(GND), .DINB4(GND), 
        .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND), 
        .WIDTHA0(GND), .WIDTHA1(GND), .WIDTHB0(GND), .WIDTHB1(GND)
        , .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), 
        .BLKA(WEAP), .BLKB(WEBP), .WENA(GND), .WENB(VCC), .CLKA(
        WCLK), .CLKB(RCLK), .RESET(VCC), .DOUTA8(), .DOUTA7(), 
        .DOUTA6(), .DOUTA5(), .DOUTA4(), .DOUTA3(), .DOUTA2(), 
        .DOUTA1(), .DOUTA0(), .DOUTB8(), .DOUTB7(), .DOUTB6(), 
        .DOUTB5(), .DOUTB4(), .DOUTB3(), .DOUTB2(), .DOUTB1(), 
        .DOUTB0(RD[11]));
    
endmodule

// _Disclaimer: Please leave the following comments in the file, they are for internal purposes only._


// _GEN_File_Contents_

// Version:9.1.0.22
// ACTGENU_CALL:1
// BATCH:T
// FAM:ProASIC3E
// OUTFORMAT:Verilog
// LPMTYPE:LPM_RAM
// LPM_HINT:TWO
// INSERT_PAD:NO
// INSERT_IOREG:NO
// GEN_BHV_VHDL_VAL:F
// GEN_BHV_VERILOG_VAL:F
// MGNTIMER:F
// MGNCMPL:T
// DESDIR:T:/Test Working/KIK2-MSVisualStudio/VMS/100015532/Firmware/100015532TFW.Actel/smartgen\Ram4096x16_TPort
// GEN_BEHV_MODULE:T
// SMARTGEN_DIE:
// SMARTGEN_PACKAGE:
// AGENIII_IS_SUBPROJECT_LIBERO:T
// WWIDTH:16
// WDEPTH:4096
// RWIDTH:16
// RDEPTH:4096
// CLKS:2
// RESET_POLARITY:2
// INIT_RAM:F
// DEFAULT_WORD:0x0000
// CASCADE:0
// WCLK_EDGE:RISE
// RCLK_EDGE:RISE
// WCLOCK_PN:WCLK
// RCLOCK_PN:RCLK
// PMODE2:0
// DATA_IN_PN:WD
// WADDRESS_PN:WADDR
// WE_PN:WEN
// DATA_OUT_PN:RD
// RADDRESS_PN:RADDR
// RE_PN:REN
// WE_POLARITY:1
// RE_POLARITY:1
// PTYPE:1

// _End_Comments_

